### ISSUE TITLE
Confused in the data folder?

### ISSUE THREAD

**Issue by mmliu202210** [Allenem/SSL4DSA#2]
You also, I would like to ask about the label in the data folder, the paper describes that only 20 labels are needed, why do you need to enter 150 labels, and what should be in the skeleton folder? Looking forward to hearing from you!

**Comment by Allenem** [comment]
1. You can see, we only used the **labeled_bs** labels to calculate the supervise loss during training.
https://github.com/Allenem/SSL4DSA/blob/7d529fd14e765cec4e12f2eedc3391c3acc09583/code/train_semisupervised_CNN_Transformer_PLCL.py#L328-L346
2. The skeleton folder was designed for another mission about the coronary artery centerline extraction. You can ignore it.

I hope you could be satisfied with my answer

**Comment by mmliu202210** [comment]
Thank you very much for your answer! Have you encountered this problem? How do I fix this?
``
(SSL4DSA) lm@ubuntu:~/project/SSL4DSA-main/code$ python train_semisupervised_CNN_Transformer_PLCL.py --root_path='../data/CA_DSA/LCA/' --exp='semisupervised/CNN_Transformer_PLCL/unet4out_isunetv5/LCA' --nets='unet4out_isunetv5' --batch_size=2 --gpus='1,2' --labeled_num=20
InceptionSwinUnet initialization parameters----depths: [2, 2, 4], depths_decoder: [0, 2, 2], num_heads: [3, 6, 12], num_classes: 2
/mnt/99247d91-0f6b-7e41-b405-f664d2eed5ef/students/lm/anaconda3/envs/SSL4DSA/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
total 100 samples for train
total 50 samples for test
  3%|▉                             | 19/601 [02:56<1:29:58,  9.28s/it]cannot identify errors: index 1 is out of bounds for axis 0 with size 1
  3%|▉                             | 20/601 [03:14<1:56:09, 12.00s/it]cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
  3%|█                             | 21/601 [03:25<1:52:06, 11.60s/it]cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
  4%|█                             | 22/601 [03:36<1:49:39, 11.36s/it]cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
  4%|█▏                            | 23/601 [03:46<1:47:25, 11.15s/it]cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
cannot identify errors: index 1 is out of bounds for axis 0 with size 1
  4%|█▏                            | 23/601 [03:57<1:39:30, 10.33s/it]
Traceback (most recent call last):
  File "train_semisupervised_CNN_Transformer_PLCL.py", line 551, in <module>
    loss.backward()  # 反向传播，计算梯度
  File "/mnt/99247d91-0f6b-7e41-b405-f664d2eed5ef/students/lm/anaconda3/envs/SSL4DSA/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/mnt/99247d91-0f6b-7e41-b405-f664d2eed5ef/students/lm/anaconda3/envs/SSL4DSA/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

**Comment by Allenem** [comment]
It seems like the dimention index 1 is out of bounds, because `cannot identify errors: index 1 is out of bounds for axis 0 with size 1` during  `loss.backward()`. I suggest you check the **shapes of input image, input label, each loss, images used for calculating loss, lables used for calculating loss**. You could print their shapes one by one, and check the sentence which used `index 1 in axis 0` meanwhile.

**Comment by mmliu202210** [comment]
Thank you very much for your answer! Have you encountered this problem? How do I fix this?
Traceback (most recent call last):
  File "train_semisupervised_CNN_Transformer_PLCL.py", line 559, in <module>
    loss.backward()  # 反向传播，计算梯度
  File "/mnt/99247d91-0f6b-7e41-b405-f664d2eed5ef/students/lm/anaconda3/envs/SSL4DSA/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/mnt/99247d91-0f6b-7e41-b405-f664d2eed5ef/students/lm/anaconda3/envs/SSL4DSA/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
